M48
; DRILL file {KiCad 8.0.7-8.0.7-0~ubuntu22.04.1} date 2025-01-12T13:00:54-0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-12T13:00:54-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7-8.0.7-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X0.9545Y-0.2044
X1.1455Y-0.2044
T2
X0.9427Y-0.0851
X1.1573Y-0.0851
M30
